# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: 'push'

defaults:
  run:
    working-directory: 'WebServiceEngFE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'WebServiceEngFE'

    - name: diagnostics
      run: pwd && ls -la
      run: ls -la ../
      continue-on-error: true

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
#        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Run tests
      run: npm test
