# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - 'WebServiceEngFE/**'
      - '.github/workflows/**'

env:
  WORKDIR: ./WebServiceEngFE
  NODEVER: 18

jobs:

  node-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ env.WORKDIR }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODEVER }}
        node-version-file: ${{ env.WORKDIR }}/package.json
        cache: 'npm'
        cache-dependency-path: ${{ env.WORKDIR }}/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Run tests
      run: npm test
